language: node_js
node_js:
  - "stable"
before_install:
  - npm update
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
  - cat ./coverage/lcov.info
